language: rust
sudo: false
addons:
  apt:
    packages:
    - gcc-arm-linux-gnueabihf
rust:
- nightly
- beta
- 1.4.0
os:
- osx
- linux
env:
  matrix:
  - TEST_FEATURES=false
  - TEST_FEATURES=true
matrix:
    #  include:
    #  - os: linux
    #    env: TARGET=arm-unknown-linux-gnueabihf TEST_FEATURES=true
    #    rust: 1.4.0
  exclude:
  - os: osx
    env: TEST_FEATURES=true
before_install:
- ./openssl/test/build.sh
script:
- ./openssl/test/run.sh
