language: rust
env:
  matrix:
    - FEATURES=""
    - FEATURES="tlsv1_1 tlsv1_2 aes_xts"
os:
  - osx
  - linux
before_script:
  - openssl s_server -accept 15418 -www -cert test/cert.pem -key test/key.pem >/dev/null 2>&1 &
script:
  - cargo test --features "$FEATURES"
