language: rust
sudo: required
rust: stable
dist: trusty

env:
  global:
    - TARGET=x86_64-unknown-linux-gnu
    - BUILD_OPENSSL_VERSION=1.0.1u
matrix:
  include:
    # osx
    - os: osx
      env: TARGET=x86_64-apple-darwin

    # ARM-bit version compat
    - env: >
        TARGET=arm-unknown-linux-gnueabihf
        BUILD_OPENSSL_VERSION=1.0.2k
        CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
        QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf
        RUST_TEST_THREADS=1
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabihf
            - qemu-user-static
            - libc6-dev-armhf-cross
            - binfmt-support
    - env: >
        TARGET=arm-unknown-linux-gnueabihf
        BUILD_OPENSSL_VERSION=1.1.0e
        CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
        QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf
        RUST_TEST_THREADS=1
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabihf
            - qemu-user-static
            - libc6-dev-armhf-cross
            - binfmt-support

    # Minimum version supported
    - rust: 1.10.0

    # beta/nightly channels
    - rust: beta
    - rust: nightly

    # 64-bit version compat
    - env: BUILD_OPENSSL_VERSION=1.0.2k
    - env: BUILD_OPENSSL_VERSION=1.1.0e

    # 32-bit version compat
    - env: TARGET=i686-unknown-linux-gnu BUILD_OPENSSL_VERSION=1.0.1u
      addons:
        apt:
          packages:
            - gcc-multilib
    - env: TARGET=i686-unknown-linux-gnu BUILD_OPENSSL_VERSION=1.0.2k
      addons:
        apt:
          packages:
            - gcc-multilib
    - env: TARGET=i686-unknown-linux-gnu BUILD_OPENSSL_VERSION=1.1.0e
      addons:
        apt:
          packages:
            - gcc-multilib

    # LibreSSL
    - env: BUILD_LIBRESSL_VERSION=2.5.0

    - env: BUILD_LIBRESSL_VERSION=2.5.4

before_install:
  - ./openssl/test/build.sh
  - rustup target add $TARGET || true
script:
  - ./openssl/test/run.sh

cache:
  cargo: true
  directories:
    - $HOME/libressl
    - $HOME/openssl
