language: rust
rust:
- nightly
- beta
- stable
os:
- osx
- linux
env:
  global:
    - FEATURES="tlsv1_2 tlsv1_1 dtlsv1 dtlsv1_2 sslv2 aes_xts npn alpn"
before_script:
- ./openssl/test/test.sh
script:
- (cd openssl && cargo test)
- (test $TRAVIS_OS_NAME == "osx" || (cd openssl && cargo test --features "$FEATURES"))
