language: rust
rust:
- nightly
- beta
- stable
os:
- osx
- linux
before_script:
- ./openssl/test/test.sh
script:
- (cd openssl && cargo test)
- (test $TRAVIS_OS_NAME == "osx" || (cd openssl && cargo test --features "$FEATURES"))
