[package]

name = "openssl"
version = "0.0.0"
authors = ["Steven Fackler <sfackler@gmail.com"]
build = "make"

[lib]

name = "openssl"
path = "src/lib.rs"

[features]
tlsv1_2 = []
tlsv1_1 = []
sslv2 = []
