[package]

name = "openssl-sys"
version = "0.0.2"
authors = ["Alex Crichton <alex@alexcrichton.com>",
           "Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "FFI bindings to OpenSSL"
repository = "https://github.com/sfackler/rust-openssl"

links = "openssl"
build = "src/build.rs"

[features]
tlsv1_2 = []
tlsv1_1 = []
sslv2 = []
aes_xts = []

[build-dependencies]
pkg-config = "*"
