[package]
name = "openssl-sys"
version = "0.7.14"
authors = ["Alex Crichton <alex@alexcrichton.com>",
           "Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "FFI bindings to OpenSSL"
repository = "https://github.com/sfackler/rust-openssl"
documentation = "https://sfackler.github.io/rust-openssl/doc/v0.7.14/openssl_sys"
links = "openssl"
build = "build.rs"

[features]
tlsv1_2 = []
tlsv1_1 = []
dtlsv1 = []
dtlsv1_2 = []
sslv2 = []
sslv3 = []
aes_xts = []
aes_ctr = []
npn = []
alpn = []
rfc5114 = []
pkcs5_pbkdf2_hmac = []

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"

[target.le32-unknown-nacl.dependencies]
libressl-pnacl-sys = "2.1.0"
[target.x86_64-unknown-nacl.dependencies]
libressl-pnacl-sys = "2.1.0"
[target.i686-unknown-nacl.dependencies]
libressl-pnacl-sys = "2.1.0"
[target.arm-unknown-nacl.dependencies]
libressl-pnacl-sys = "2.1.0"

# Only here to make sure we link to these in a static build on Windows
[target.i686-pc-windows-gnu.dependencies]
user32-sys = "0.2"
gdi32-sys = "0.2"
[target.x86_64-pc-windows-gnu.dependencies]
user32-sys = "0.2"
gdi32-sys = "0.2"
[target.i686-pc-windows-msvc.dependencies]
user32-sys = "0.2"
gdi32-sys = "0.2"
[target.x86_64-pc-windows-msvc.dependencies]
user32-sys = "0.2"
gdi32-sys = "0.2"
